CREATE TABLE `employee` (
  `EMPLOYEE_ID` int NOT NULL,
  `EMPLOYEE_NAME` varchar(50) NOT NULL,
  `CONTACT_NO` int NOT NULL,
  `EMAIL_ID` varchar(45) NOT NULL,
  `JOINING_DATE` date NOT NULL,
  `SALARY` int NOT NULL,
  `AADHAR_ID` int NOT NULL,
  `DOB` date NOT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`),
  UNIQUE KEY `CONTACT_NO_UNIQUE` (`CONTACT_NO`),
  UNIQUE KEY `EMAIL_ID_UNIQUE` (`EMAIL_ID`),
  UNIQUE KEY `AADHAR_ID_UNIQUE` (`AADHAR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `donar` (
  `DONAR_ID` int NOT NULL,
  `EMPLOYEE_ID` int NOT NULL,
  `DONAR_NAME` varchar(50) NOT NULL,
  `AADHAR_ID` int NOT NULL,
  `ADDRESS` varchar(200) NOT NULL,
  `CONTACT_NO` int NOT NULL,
  `ITEM_TYPE` varchar(45) NOT NULL,
  `ITEM_NAME` varchar(45) NOT NULL,
  `QUANTITY` int NOT NULL,
  PRIMARY KEY (`DONAR_ID`),
  UNIQUE KEY `AADHAR_ID_UNIQUE` (`AADHAR_ID`),
  UNIQUE KEY `CONTACT_NO_UNIQUE` (`CONTACT_NO`),
  KEY `EMPLOYEE_ID_idx` (`EMPLOYEE_ID`),
  CONSTRAINT `EMPLOYEE_ID` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `volunteer` (
  `VOLUNTEER_ID` int NOT NULL,
  `EMPLOYEE_ID` int NOT NULL,
  `VOLUNTEER_NAME` varchar(45) NOT NULL,
  `CONTACT_NO` int NOT NULL,
  `NO_OF_HRS` int NOT NULL,
  PRIMARY KEY (`VOLUNTEER_ID`),
  UNIQUE KEY `CONTACT_NO_UNIQUE` (`CONTACT_NO`),
  KEY `EMPLOYEE_ID_idx` (`EMPLOYEE_ID`),
  CONSTRAINT `EMPLOYEE_ID2` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `food_bank` (
  `ITEM_TYPE` varchar(45) NOT NULL,
  `ITEM_NAME` varchar(45) NOT NULL,
  `QUANTITY` int NOT NULL,
  `EXPIRY` date DEFAULT NULL,
  PRIMARY KEY (`ITEM_TYPE`,`ITEM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE `dbms_project`.`food_bank` 
ADD INDEX `ITEM_NAME` (`ITEM_NAME` ASC) VISIBLE;

CREATE TABLE `donation` (
  `DONAR_ID` int NOT NULL,
  `ITEM_TYPE` varchar(45) NOT NULL,
  `ITEM_NAME` varchar(45) NOT NULL,
  PRIMARY KEY (`DONAR_ID`,`ITEM_TYPE`,`ITEM_NAME`),
  KEY `ITEM_TYPE_idx` (`ITEM_TYPE`),
  KEY `ITEM_NAME_idx` (`ITEM_NAME`),
  CONSTRAINT `DONAR_ID` FOREIGN KEY (`DONAR_ID`) REFERENCES `donar` (`DONAR_ID`),
  CONSTRAINT `ITEM_NAME` FOREIGN KEY (`ITEM_NAME`) REFERENCES `food_bank` (`ITEM_NAME`),
  CONSTRAINT `ITEM_TYPE` FOREIGN KEY (`ITEM_TYPE`) REFERENCES `food_bank` (`ITEM_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `donee` (
  `DONEE_ID` int NOT NULL,
  `DONEE_NAME` varchar(45) NOT NULL,
  `ITEM_TYPE` varchar(45) NOT NULL,
  `ITEM_NAME` varchar(45) NOT NULL,
  `QUANTITY` varchar(45) NOT NULL,
  `VOLUNTER_ID` int NOT NULL,
  PRIMARY KEY (`DONEE_ID`),
  KEY `ITEM_NAME4_idx` (`ITEM_NAME`),
  KEY `ITEM_TYPE4_idx` (`ITEM_TYPE`),
  KEY `VOLUNTEER_ID` (`VOLUNTER_ID`),
  CONSTRAINT `ITEM_NAME4` FOREIGN KEY (`ITEM_NAME`) REFERENCES `food_bank` (`ITEM_NAME`),
  CONSTRAINT `ITEM_TYPE4` FOREIGN KEY (`ITEM_TYPE`) REFERENCES `food_bank` (`ITEM_TYPE`),
  CONSTRAINT `VOLUNTEER_ID` FOREIGN KEY (`VOLUNTER_ID`) REFERENCES `volunteer` (`VOLUNTEER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `produced` (
  `ITEM_NAME` varchar(45) NOT NULL,
  `QUANTITY` int NOT NULL,
  `EXPIRY` date NOT NULL,
  PRIMARY KEY (`ITEM_NAME`),
  CONSTRAINT `ITEM_NAME1` FOREIGN KEY (`ITEM_NAME`) REFERENCES `food_bank` (`ITEM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



CREATE TABLE `grain` (
  `ITEM_NAME` varchar(45) NOT NULL,
  `QUANTITY` int NOT NULL,
  PRIMARY KEY (`ITEM_NAME`),
  CONSTRAINT `ITEM_NAME2` FOREIGN KEY (`ITEM_NAME`) REFERENCES `food_bank` (`ITEM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `pulses` (
  `ITEM_NAME` varchar(45) NOT NULL,
  `QUANTITY` int DEFAULT NULL,
  PRIMARY KEY (`ITEM_NAME`),
  CONSTRAINT `ITEM_NAME3` FOREIGN KEY (`ITEM_NAME`) REFERENCES `food_bank` (`ITEM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


