CREATE TABLE `user_details` (
  `user_name` varchar(200) NOT NULL,
  `user_email` varchar(500) NOT NULL,
  `password` varchar(100) NOT NULL,
  PRIMARY KEY (`user_name`),
  UNIQUE KEY `user_name_UNIQUE` (`user_name`),
  UNIQUE KEY `user_email_UNIQUE` (`user_email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;




CREATE TABLE `employee` (
  `EMPLOYEE_ID` varchar(45) NOT NULL,
  `EMPLOYEE_NAME` varchar(50) NOT NULL,
  `CONTACT_NO` varchar(45) NOT NULL,
  `EMAIL_ID` varchar(45) NOT NULL,
  `JOINING_DATE` date NOT NULL,
  `SALARY` int NOT NULL,
  `AADHAR_ID` int NOT NULL,
  `DOB` date NOT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`),
  UNIQUE KEY `CONTACT_NO_UNIQUE` (`CONTACT_NO`),
  UNIQUE KEY `EMAIL_ID_UNIQUE` (`EMAIL_ID`),
  UNIQUE KEY `AADHAR_ID_UNIQUE` (`AADHAR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `volunteer` (
  `VOLUNTEER_ID` varchar(45) NOT NULL,
  `EMPLOYEE_ID` varchar(45) NOT NULL,
  `VOLUNTEER_NAME` varchar(45) NOT NULL,
  `CONTACT_NO` varchar(45) NOT NULL,
  `NO_OF_HRS` int NOT NULL,
  PRIMARY KEY (`VOLUNTEER_ID`),
  UNIQUE KEY `CONTACT_NO_UNIQUE` (`CONTACT_NO`),
  KEY `EMPLOYEE_ID_idx` (`EMPLOYEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `donar` (
  `DONAR_ID` varchar(45) NOT NULL,
  `EMPLOYEE_ID` varchar(45) NOT NULL,
  `DONAR_NAME` varchar(45) NOT NULL,
  `AADHAR_ID` int NOT NULL,
  `ADDRESS` varchar(200) NOT NULL,
  `CONTACT_NO` varchar(45) NOT NULL,
  PRIMARY KEY (`DONAR_ID`),
  UNIQUE KEY `CONTACT_NO_UNIQUE` (`CONTACT_NO`),
  KEY `EMPLOYEE_ID_idx` (`EMPLOYEE_ID`),
  CONSTRAINT `EMPLOYEE_ID` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `employee` (`EMPLOYEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `donation` (
  `DONAR_ID` varchar(45) NOT NULL,
  `ITEM_TYPE` varchar(45) NOT NULL,
  `ITEM_NAME` varchar(45) NOT NULL,
  `QUANTITY` int NOT NULL,
  `ENTRY_DATE` date NOT NULL,
  PRIMARY KEY (`DONAR_ID`,`ITEM_TYPE`,`ITEM_NAME`),
  KEY `DONAR_ID_idx` (`DONAR_ID`),
  CONSTRAINT `DONAR_ID` FOREIGN KEY (`DONAR_ID`) REFERENCES `donar` (`DONAR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `food_bank` (
  `ITEM_TYPE` varchar(45) NOT NULL,
  `ITEM_NAME` varchar(45) NOT NULL,
  `QUANTITY` int NOT NULL,
  PRIMARY KEY (`ITEM_TYPE`,`ITEM_NAME`),
  KEY `ITEM_NAME` (`ITEM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `donee` (
  `VOLUNTEER_ID` varchar(45) NOT NULL,
  `DONEE_ID` varchar(45) NOT NULL,
  `DONEE_NAME` varchar(45) NOT NULL,
  `CONTACT_NO` varchar(45) NOT NULL,
  `AADHAR_ID` int NOT NULL,
  PRIMARY KEY (`DONEE_ID`),
  UNIQUE KEY `CONTACT_NO_UNIQUE` (`CONTACT_NO`),
  UNIQUE KEY `AADHAR_ID_UNIQUE` (`AADHAR_ID`),
  KEY `VOLUNTEER_ID1_idx` (`VOLUNTEER_ID`),
  CONSTRAINT `VOLUNTEER_ID1` FOREIGN KEY (`VOLUNTEER_ID`) REFERENCES `volunteer` (`VOLUNTEER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `donated` (
  `DONEE_ID` varchar(45) NOT NULL,
  `ITEM_TYPE` varchar(45) NOT NULL,
  `ITEM_NAME` varchar(45) NOT NULL,
  `QUANTITY` varchar(45) NOT NULL,
  `DONATION_DATE` date NOT NULL,
  PRIMARY KEY (`DONEE_ID`,`ITEM_TYPE`,`ITEM_NAME`),
  KEY `ITEM_TYPE_idx` (`ITEM_TYPE`),
  KEY `ITEM_NAME_idx` (`ITEM_NAME`),
  CONSTRAINT `DONEE_ID` FOREIGN KEY (`DONEE_ID`) REFERENCES `donee` (`DONEE_ID`),
  CONSTRAINT `ITEM_NAME` FOREIGN KEY (`ITEM_NAME`) REFERENCES `food_bank` (`ITEM_NAME`),
  CONSTRAINT `ITEM_TYPE` FOREIGN KEY (`ITEM_TYPE`) REFERENCES `food_bank` (`ITEM_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



CREATE TABLE `produced` (
  `ITEM_NAME` varchar(45) NOT NULL,
  `QUANTITY` int NOT NULL,
  PRIMARY KEY (`ITEM_NAME`),
  CONSTRAINT `ITEM_NAME1` FOREIGN KEY (`ITEM_NAME`) REFERENCES `food_bank` (`ITEM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



CREATE TABLE `grain` (
  `ITEM_NAME` varchar(45) NOT NULL,
  `QUANTITY` int NOT NULL,
  PRIMARY KEY (`ITEM_NAME`),
  CONSTRAINT `ITEM_NAME2` FOREIGN KEY (`ITEM_NAME`) REFERENCES `food_bank` (`ITEM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `pulses` (
  `ITEM_NAME` varchar(45) NOT NULL,
  `QUANTITY` int DEFAULT NULL,
  PRIMARY KEY (`ITEM_NAME`),
  CONSTRAINT `ITEM_NAME3` FOREIGN KEY (`ITEM_NAME`) REFERENCES `food_bank` (`ITEM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;




